// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: APIOcoOrderCancelReplyMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ctrade.Message {

  /// <summary>Holder for reflection information generated from APIOcoOrderCancelReplyMsg.proto</summary>
  public static partial class APIOcoOrderCancelReplyMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for APIOcoOrderCancelReplyMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static APIOcoOrderCancelReplyMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9BUElPY29PcmRlckNhbmNlbFJlcGx5TXNnLnByb3RvEg5jdHJhZGUubWVz",
            "c2FnZRoOc3RhbmRhcmQucHJvdG8aDEhlYWRlci5wcm90bxoKVXNlci5wcm90",
            "byKgAQoWQVBJT2NvT3JkZXJDYW5jZWxSZXBseRIQCghvcmRlcl9JRBgBIAEo",
            "CRITCgtleGVjX29yZ19pZBgCIAIoCRIUCgxleGVjX3VzZXJfaWQYAyACKAkS",
            "FwoPZXhlY19hY2tfc3RhdHVzGAQgAigJEgwKBHRleHQYByABKAkSIgoEdXNl",
            "chhkIAIoCzIULmN0cmFkZS5tZXNzYWdlLlVzZXIieQoZQVBJT2NvT3JkZXJD",
            "YW5jZWxSZXBseU1zZxImCgZoZWFkZXIYASABKAsyFi5jdHJhZGUubWVzc2Fn",
            "ZS5IZWFkZXISNAoEYm9keRgCIAEoCzImLmN0cmFkZS5tZXNzYWdlLkFQSU9j",
            "b09yZGVyQ2FuY2VsUmVwbHlCOAoVY24uY29tLmNmZXRzLmRhdGEubXNnQh9B",
            "UElPY29PcmRlckNhbmNlbFJlcGx5TXNnUHJvYnVm"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::StandardReflection.Descriptor, global::Ctrade.Message.HeaderReflection.Descriptor, global::Ctrade.Message.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOcoOrderCancelReply), global::Ctrade.Message.APIOcoOrderCancelReply.Parser, new[]{ "OrderID", "ExecOrgId", "ExecUserId", "ExecAckStatus", "Text", "User" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOcoOrderCancelReplyMsg), global::Ctrade.Message.APIOcoOrderCancelReplyMsg.Parser, new[]{ "Header", "Body" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 订单撤销反馈
  /// </summary>
  public sealed partial class APIOcoOrderCancelReply : pb::IMessage<APIOcoOrderCancelReply> {
    private static readonly pb::MessageParser<APIOcoOrderCancelReply> _parser = new pb::MessageParser<APIOcoOrderCancelReply>(() => new APIOcoOrderCancelReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOcoOrderCancelReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOcoOrderCancelReplyMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelReply(APIOcoOrderCancelReply other) : this() {
      orderID_ = other.orderID_;
      execOrgId_ = other.execOrgId_;
      execUserId_ = other.execUserId_;
      execAckStatus_ = other.execAckStatus_;
      text_ = other.text_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelReply Clone() {
      return new APIOcoOrderCancelReply(this);
    }

    /// <summary>Field number for the "order_ID" field.</summary>
    public const int OrderIDFieldNumber = 1;
    private readonly static string OrderIDDefaultValue = "";

    private string orderID_;
    /// <summary>
    ///required string order_req_id = 1; /// 订单操作参考序号
    ///required int32 order_cancel_type = 2 ; /// 订单撤销标识
    /// optional string order_seq_num = 3; /// 待撤销订单操作序列号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderID {
      get { return orderID_ ?? OrderIDDefaultValue; }
      set {
        orderID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "order_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOrderID {
      get { return orderID_ != null; }
    }
    /// <summary>Clears the value of the "order_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOrderID() {
      orderID_ = null;
    }

    /// <summary>Field number for the "exec_org_id" field.</summary>
    public const int ExecOrgIdFieldNumber = 2;
    private readonly static string ExecOrgIdDefaultValue = "";

    private string execOrgId_;
    /// <summary>
    ////执行方机构ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExecOrgId {
      get { return execOrgId_ ?? ExecOrgIdDefaultValue; }
      set {
        execOrgId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "exec_org_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasExecOrgId {
      get { return execOrgId_ != null; }
    }
    /// <summary>Clears the value of the "exec_org_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearExecOrgId() {
      execOrgId_ = null;
    }

    /// <summary>Field number for the "exec_user_id" field.</summary>
    public const int ExecUserIdFieldNumber = 3;
    private readonly static string ExecUserIdDefaultValue = "";

    private string execUserId_;
    /// <summary>
    ////执行方用户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExecUserId {
      get { return execUserId_ ?? ExecUserIdDefaultValue; }
      set {
        execUserId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "exec_user_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasExecUserId {
      get { return execUserId_ != null; }
    }
    /// <summary>Clears the value of the "exec_user_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearExecUserId() {
      execUserId_ = null;
    }

    /// <summary>Field number for the "exec_ack_status" field.</summary>
    public const int ExecAckStatusFieldNumber = 4;
    private readonly static string ExecAckStatusDefaultValue = "";

    private string execAckStatus_;
    /// <summary>
    ////处理结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExecAckStatus {
      get { return execAckStatus_ ?? ExecAckStatusDefaultValue; }
      set {
        execAckStatus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "exec_ack_status" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasExecAckStatus {
      get { return execAckStatus_ != null; }
    }
    /// <summary>Clears the value of the "exec_ack_status" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearExecAckStatus() {
      execAckStatus_ = null;
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 7;
    private readonly static string TextDefaultValue = "";

    private string text_;
    /// <summary>
    ///required int32 err_code = 5;
    ///required string err_msg = 6;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_ ?? TextDefaultValue; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "text" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasText {
      get { return text_ != null; }
    }
    /// <summary>Clears the value of the "text" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearText() {
      text_ = null;
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 100;
    private global::Ctrade.Message.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOcoOrderCancelReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOcoOrderCancelReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderID != other.OrderID) return false;
      if (ExecOrgId != other.ExecOrgId) return false;
      if (ExecUserId != other.ExecUserId) return false;
      if (ExecAckStatus != other.ExecAckStatus) return false;
      if (Text != other.Text) return false;
      if (!object.Equals(User, other.User)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOrderID) hash ^= OrderID.GetHashCode();
      if (HasExecOrgId) hash ^= ExecOrgId.GetHashCode();
      if (HasExecUserId) hash ^= ExecUserId.GetHashCode();
      if (HasExecAckStatus) hash ^= ExecAckStatus.GetHashCode();
      if (HasText) hash ^= Text.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasOrderID) {
        output.WriteRawTag(10);
        output.WriteString(OrderID);
      }
      if (HasExecOrgId) {
        output.WriteRawTag(18);
        output.WriteString(ExecOrgId);
      }
      if (HasExecUserId) {
        output.WriteRawTag(26);
        output.WriteString(ExecUserId);
      }
      if (HasExecAckStatus) {
        output.WriteRawTag(34);
        output.WriteString(ExecAckStatus);
      }
      if (HasText) {
        output.WriteRawTag(58);
        output.WriteString(Text);
      }
      if (user_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(User);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOrderID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderID);
      }
      if (HasExecOrgId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExecOrgId);
      }
      if (HasExecUserId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExecUserId);
      }
      if (HasExecAckStatus) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExecAckStatus);
      }
      if (HasText) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (user_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOcoOrderCancelReply other) {
      if (other == null) {
        return;
      }
      if (other.HasOrderID) {
        OrderID = other.OrderID;
      }
      if (other.HasExecOrgId) {
        ExecOrgId = other.ExecOrgId;
      }
      if (other.HasExecUserId) {
        ExecUserId = other.ExecUserId;
      }
      if (other.HasExecAckStatus) {
        ExecAckStatus = other.ExecAckStatus;
      }
      if (other.HasText) {
        Text = other.Text;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Ctrade.Message.User();
        }
        User.MergeFrom(other.User);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrderID = input.ReadString();
            break;
          }
          case 18: {
            ExecOrgId = input.ReadString();
            break;
          }
          case 26: {
            ExecUserId = input.ReadString();
            break;
          }
          case 34: {
            ExecAckStatus = input.ReadString();
            break;
          }
          case 58: {
            Text = input.ReadString();
            break;
          }
          case 802: {
            if (user_ == null) {
              User = new global::Ctrade.Message.User();
            }
            input.ReadMessage(User);
            break;
          }
        }
      }
    }

  }

  public sealed partial class APIOcoOrderCancelReplyMsg : pb::IMessage<APIOcoOrderCancelReplyMsg> {
    private static readonly pb::MessageParser<APIOcoOrderCancelReplyMsg> _parser = new pb::MessageParser<APIOcoOrderCancelReplyMsg>(() => new APIOcoOrderCancelReplyMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOcoOrderCancelReplyMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOcoOrderCancelReplyMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelReplyMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelReplyMsg(APIOcoOrderCancelReplyMsg other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      body_ = other.body_ != null ? other.body_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelReplyMsg Clone() {
      return new APIOcoOrderCancelReplyMsg(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Ctrade.Message.Header header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 2;
    private global::Ctrade.Message.APIOcoOrderCancelReply body_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.APIOcoOrderCancelReply Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOcoOrderCancelReplyMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOcoOrderCancelReplyMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Body, other.Body)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (body_ != null) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (body_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOcoOrderCancelReplyMsg other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Ctrade.Message.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::Ctrade.Message.APIOcoOrderCancelReply();
        }
        Body.MergeFrom(other.Body);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Ctrade.Message.Header();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (body_ == null) {
              Body = new global::Ctrade.Message.APIOcoOrderCancelReply();
            }
            input.ReadMessage(Body);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
