#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM nginx
COPY PortalWebBin/www/  /usr/share/nginx/html/
COPY PortalWebBin/nginx.conf /etc/nginx/nginx.conf
RUN chmod -R 777 *
EXPOSE 80