// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: APIOrderCancelRequestMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ctrade.Message {

  /// <summary>Holder for reflection information generated from APIOrderCancelRequestMsg.proto</summary>
  public static partial class APIOrderCancelRequestMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for APIOrderCancelRequestMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static APIOrderCancelRequestMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5BUElPcmRlckNhbmNlbFJlcXVlc3RNc2cucHJvdG8SDmN0cmFkZS5tZXNz",
            "YWdlGg5zdGFuZGFyZC5wcm90bxoMSGVhZGVyLnByb3RvGgpVc2VyLnByb3Rv",
            "IpUBChVBUElPcmRlckNhbmNlbFJlcXVlc3QSFAoMb3JkZXJfcmVxX2lkGAEg",
            "AigJEhkKEW9yZGVyX2NhbmNlbF90eXBlGAIgAigFEhUKDW9yZGVyX3NlcV9u",
            "dW0YAyABKAkSEAoIb3JkZXJfSUQYBCABKAkSIgoEdXNlchhkIAIoCzIULmN0",
            "cmFkZS5tZXNzYWdlLlVzZXIidwoYQVBJT3JkZXJDYW5jZWxSZXF1ZXN0TXNn",
            "EiYKBmhlYWRlchgBIAEoCzIWLmN0cmFkZS5tZXNzYWdlLkhlYWRlchIzCgRi",
            "b2R5GAIgASgLMiUuY3RyYWRlLm1lc3NhZ2UuQVBJT3JkZXJDYW5jZWxSZXF1",
            "ZXN0QjcKFWNuLmNvbS5jZmV0cy5kYXRhLm1zZ0IeQVBJT3JkZXJDYW5jZWxS",
            "ZXF1ZXN0TXNnUHJvYnVm"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::StandardReflection.Descriptor, global::Ctrade.Message.HeaderReflection.Descriptor, global::Ctrade.Message.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOrderCancelRequest), global::Ctrade.Message.APIOrderCancelRequest.Parser, new[]{ "OrderReqId", "OrderCancelType", "OrderSeqNum", "OrderID", "User" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOrderCancelRequestMsg), global::Ctrade.Message.APIOrderCancelRequestMsg.Parser, new[]{ "Header", "Body" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///cancle order message
  /// </summary>
  public sealed partial class APIOrderCancelRequest : pb::IMessage<APIOrderCancelRequest> {
    private static readonly pb::MessageParser<APIOrderCancelRequest> _parser = new pb::MessageParser<APIOrderCancelRequest>(() => new APIOrderCancelRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOrderCancelRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOrderCancelRequestMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOrderCancelRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOrderCancelRequest(APIOrderCancelRequest other) : this() {
      _hasBits0 = other._hasBits0;
      orderReqId_ = other.orderReqId_;
      orderCancelType_ = other.orderCancelType_;
      orderSeqNum_ = other.orderSeqNum_;
      orderID_ = other.orderID_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOrderCancelRequest Clone() {
      return new APIOrderCancelRequest(this);
    }

    /// <summary>Field number for the "order_req_id" field.</summary>
    public const int OrderReqIdFieldNumber = 1;
    private readonly static string OrderReqIdDefaultValue = "";

    private string orderReqId_;
    /// <summary>
    /// order operation seqno
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderReqId {
      get { return orderReqId_ ?? OrderReqIdDefaultValue; }
      set {
        orderReqId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "order_req_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOrderReqId {
      get { return orderReqId_ != null; }
    }
    /// <summary>Clears the value of the "order_req_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOrderReqId() {
      orderReqId_ = null;
    }

    /// <summary>Field number for the "order_cancel_type" field.</summary>
    public const int OrderCancelTypeFieldNumber = 2;
    private readonly static int OrderCancelTypeDefaultValue = 0;

    private int orderCancelType_;
    /// <summary>
    /// order cancle type
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int OrderCancelType {
      get { if ((_hasBits0 & 1) != 0) { return orderCancelType_; } else { return OrderCancelTypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        orderCancelType_ = value;
      }
    }
    /// <summary>Gets whether the "order_cancel_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOrderCancelType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "order_cancel_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOrderCancelType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "order_seq_num" field.</summary>
    public const int OrderSeqNumFieldNumber = 3;
    private readonly static string OrderSeqNumDefaultValue = "";

    private string orderSeqNum_;
    /// <summary>
    /// order submit seqno
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderSeqNum {
      get { return orderSeqNum_ ?? OrderSeqNumDefaultValue; }
      set {
        orderSeqNum_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "order_seq_num" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOrderSeqNum {
      get { return orderSeqNum_ != null; }
    }
    /// <summary>Clears the value of the "order_seq_num" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOrderSeqNum() {
      orderSeqNum_ = null;
    }

    /// <summary>Field number for the "order_ID" field.</summary>
    public const int OrderIDFieldNumber = 4;
    private readonly static string OrderIDDefaultValue = "";

    private string orderID_;
    /// <summary>
    /// cancle order id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderID {
      get { return orderID_ ?? OrderIDDefaultValue; }
      set {
        orderID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "order_ID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOrderID {
      get { return orderID_ != null; }
    }
    /// <summary>Clears the value of the "order_ID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOrderID() {
      orderID_ = null;
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 100;
    private global::Ctrade.Message.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOrderCancelRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOrderCancelRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderReqId != other.OrderReqId) return false;
      if (OrderCancelType != other.OrderCancelType) return false;
      if (OrderSeqNum != other.OrderSeqNum) return false;
      if (OrderID != other.OrderID) return false;
      if (!object.Equals(User, other.User)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOrderReqId) hash ^= OrderReqId.GetHashCode();
      if (HasOrderCancelType) hash ^= OrderCancelType.GetHashCode();
      if (HasOrderSeqNum) hash ^= OrderSeqNum.GetHashCode();
      if (HasOrderID) hash ^= OrderID.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasOrderReqId) {
        output.WriteRawTag(10);
        output.WriteString(OrderReqId);
      }
      if (HasOrderCancelType) {
        output.WriteRawTag(16);
        output.WriteInt32(OrderCancelType);
      }
      if (HasOrderSeqNum) {
        output.WriteRawTag(26);
        output.WriteString(OrderSeqNum);
      }
      if (HasOrderID) {
        output.WriteRawTag(34);
        output.WriteString(OrderID);
      }
      if (user_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(User);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOrderReqId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderReqId);
      }
      if (HasOrderCancelType) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OrderCancelType);
      }
      if (HasOrderSeqNum) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderSeqNum);
      }
      if (HasOrderID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderID);
      }
      if (user_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOrderCancelRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasOrderReqId) {
        OrderReqId = other.OrderReqId;
      }
      if (other.HasOrderCancelType) {
        OrderCancelType = other.OrderCancelType;
      }
      if (other.HasOrderSeqNum) {
        OrderSeqNum = other.OrderSeqNum;
      }
      if (other.HasOrderID) {
        OrderID = other.OrderID;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Ctrade.Message.User();
        }
        User.MergeFrom(other.User);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrderReqId = input.ReadString();
            break;
          }
          case 16: {
            OrderCancelType = input.ReadInt32();
            break;
          }
          case 26: {
            OrderSeqNum = input.ReadString();
            break;
          }
          case 34: {
            OrderID = input.ReadString();
            break;
          }
          case 802: {
            if (user_ == null) {
              User = new global::Ctrade.Message.User();
            }
            input.ReadMessage(User);
            break;
          }
        }
      }
    }

  }

  public sealed partial class APIOrderCancelRequestMsg : pb::IMessage<APIOrderCancelRequestMsg> {
    private static readonly pb::MessageParser<APIOrderCancelRequestMsg> _parser = new pb::MessageParser<APIOrderCancelRequestMsg>(() => new APIOrderCancelRequestMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOrderCancelRequestMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOrderCancelRequestMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOrderCancelRequestMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOrderCancelRequestMsg(APIOrderCancelRequestMsg other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      body_ = other.body_ != null ? other.body_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOrderCancelRequestMsg Clone() {
      return new APIOrderCancelRequestMsg(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Ctrade.Message.Header header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 2;
    private global::Ctrade.Message.APIOrderCancelRequest body_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.APIOrderCancelRequest Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOrderCancelRequestMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOrderCancelRequestMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Body, other.Body)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (body_ != null) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (body_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOrderCancelRequestMsg other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Ctrade.Message.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::Ctrade.Message.APIOrderCancelRequest();
        }
        Body.MergeFrom(other.Body);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Ctrade.Message.Header();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (body_ == null) {
              Body = new global::Ctrade.Message.APIOrderCancelRequest();
            }
            input.ReadMessage(Body);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
