// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: APIOcoOrderSumitReplyMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ctrade.Message {

  /// <summary>Holder for reflection information generated from APIOcoOrderSumitReplyMsg.proto</summary>
  public static partial class APIOcoOrderSumitReplyMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for APIOcoOrderSumitReplyMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static APIOcoOrderSumitReplyMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5BUElPY29PcmRlclN1bWl0UmVwbHlNc2cucHJvdG8SDmN0cmFkZS5tZXNz",
            "YWdlGg5zdGFuZGFyZC5wcm90bxoMSGVhZGVyLnByb3RvGgpVc2VyLnByb3Rv",
            "IioKFkFQSU9jb09yZGVyU3VibWl0UmVwbHkSEAoIb3JkZXJfaWQYASACKAki",
            "5QEKFUFQSU9jb09yZGVyU3VtaXRSZXBseRILCgNta3QYASACKAUSFwoPZXhl",
            "Y19hY2tfc3RhdHVzGAIgAigJEhEKCXRyYW5fdGltZRgDIAEoCRIUCgxvcmRl",
            "cl9yZXFfaWQYBiABKAkSDAoEdGV4dBgHIAEoCRIUCgxvY29fb3JkZXJfbm8Y",
            "CCABKAMSNgoGb3JkZXJzGGIgAygLMiYuY3RyYWRlLm1lc3NhZ2UuQVBJT2Nv",
            "T3JkZXJTdWJtaXRSZXBseRIhCgN1c3IYZCACKAsyFC5jdHJhZGUubWVzc2Fn",
            "ZS5Vc2VyIncKGEFQSU9jb09yZGVyU3VtaXRSZXBseU1zZxImCgZoZWFkZXIY",
            "ASABKAsyFi5jdHJhZGUubWVzc2FnZS5IZWFkZXISMwoEYm9keRgCIAEoCzIl",
            "LmN0cmFkZS5tZXNzYWdlLkFQSU9jb09yZGVyU3VtaXRSZXBseUJlCiBjbi5j",
            "b20uY2ZldHMuZGF0YS5jdHJhZGUubWVzc2FnZUIfQVBJT2NvT3JkZXJTdWJt",
            "aXRSZXBseU1zZ1Byb2J1ZoK1GB5DVFJBREUtT1JERVItREFUQS1TVUJNSVQt",
            "UkVQTFk="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::StandardReflection.Descriptor, global::Ctrade.Message.HeaderReflection.Descriptor, global::Ctrade.Message.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOcoOrderSubmitReply), global::Ctrade.Message.APIOcoOrderSubmitReply.Parser, new[]{ "OrderId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOcoOrderSumitReply), global::Ctrade.Message.APIOcoOrderSumitReply.Parser, new[]{ "Mkt", "ExecAckStatus", "TranTime", "OrderReqId", "Text", "OcoOrderNo", "Orders", "Usr" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOcoOrderSumitReplyMsg), global::Ctrade.Message.APIOcoOrderSumitReplyMsg.Parser, new[]{ "Header", "Body" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 订单提交反馈
  /// </summary>
  public sealed partial class APIOcoOrderSubmitReply : pb::IMessage<APIOcoOrderSubmitReply> {
    private static readonly pb::MessageParser<APIOcoOrderSubmitReply> _parser = new pb::MessageParser<APIOcoOrderSubmitReply>(() => new APIOcoOrderSubmitReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOcoOrderSubmitReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOcoOrderSumitReplyMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSubmitReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSubmitReply(APIOcoOrderSubmitReply other) : this() {
      orderId_ = other.orderId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSubmitReply Clone() {
      return new APIOcoOrderSubmitReply(this);
    }

    /// <summary>Field number for the "order_id" field.</summary>
    public const int OrderIdFieldNumber = 1;
    private readonly static string OrderIdDefaultValue = "";

    private string orderId_;
    /// <summary>
    ///required string exec_ack_status = 1;	//处理结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderId {
      get { return orderId_ ?? OrderIdDefaultValue; }
      set {
        orderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "order_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOrderId {
      get { return orderId_ != null; }
    }
    /// <summary>Clears the value of the "order_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOrderId() {
      orderId_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOcoOrderSubmitReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOcoOrderSubmitReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderId != other.OrderId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOrderId) hash ^= OrderId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasOrderId) {
        output.WriteRawTag(10);
        output.WriteString(OrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOrderId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOcoOrderSubmitReply other) {
      if (other == null) {
        return;
      }
      if (other.HasOrderId) {
        OrderId = other.OrderId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OrderId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// OCO订单提交(ME)
  /// </summary>
  public sealed partial class APIOcoOrderSumitReply : pb::IMessage<APIOcoOrderSumitReply> {
    private static readonly pb::MessageParser<APIOcoOrderSumitReply> _parser = new pb::MessageParser<APIOcoOrderSumitReply>(() => new APIOcoOrderSumitReply());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOcoOrderSumitReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOcoOrderSumitReplyMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSumitReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSumitReply(APIOcoOrderSumitReply other) : this() {
      _hasBits0 = other._hasBits0;
      mkt_ = other.mkt_;
      execAckStatus_ = other.execAckStatus_;
      tranTime_ = other.tranTime_;
      orderReqId_ = other.orderReqId_;
      text_ = other.text_;
      ocoOrderNo_ = other.ocoOrderNo_;
      orders_ = other.orders_.Clone();
      usr_ = other.usr_ != null ? other.usr_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSumitReply Clone() {
      return new APIOcoOrderSumitReply(this);
    }

    /// <summary>Field number for the "mkt" field.</summary>
    public const int MktFieldNumber = 1;
    private readonly static int MktDefaultValue = 0;

    private int mkt_;
    /// <summary>
    /// 市场标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Mkt {
      get { if ((_hasBits0 & 1) != 0) { return mkt_; } else { return MktDefaultValue; } }
      set {
        _hasBits0 |= 1;
        mkt_ = value;
      }
    }
    /// <summary>Gets whether the "mkt" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMkt {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "mkt" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMkt() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "exec_ack_status" field.</summary>
    public const int ExecAckStatusFieldNumber = 2;
    private readonly static string ExecAckStatusDefaultValue = "";

    private string execAckStatus_;
    /// <summary>
    ///处理结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExecAckStatus {
      get { return execAckStatus_ ?? ExecAckStatusDefaultValue; }
      set {
        execAckStatus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "exec_ack_status" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasExecAckStatus {
      get { return execAckStatus_ != null; }
    }
    /// <summary>Clears the value of the "exec_ack_status" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearExecAckStatus() {
      execAckStatus_ = null;
    }

    /// <summary>Field number for the "tran_time" field.</summary>
    public const int TranTimeFieldNumber = 3;
    private readonly static string TranTimeDefaultValue = "";

    private string tranTime_;
    /// <summary>
    ///激活时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TranTime {
      get { return tranTime_ ?? TranTimeDefaultValue; }
      set {
        tranTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "tran_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasTranTime {
      get { return tranTime_ != null; }
    }
    /// <summary>Clears the value of the "tran_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTranTime() {
      tranTime_ = null;
    }

    /// <summary>Field number for the "order_req_id" field.</summary>
    public const int OrderReqIdFieldNumber = 6;
    private readonly static string OrderReqIdDefaultValue = "";

    private string orderReqId_;
    /// <summary>
    ///订单操作参考序号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrderReqId {
      get { return orderReqId_ ?? OrderReqIdDefaultValue; }
      set {
        orderReqId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "order_req_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOrderReqId {
      get { return orderReqId_ != null; }
    }
    /// <summary>Clears the value of the "order_req_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOrderReqId() {
      orderReqId_ = null;
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 7;
    private readonly static string TextDefaultValue = "";

    private string text_;
    /// <summary>
    ///失败原因
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_ ?? TextDefaultValue; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "text" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasText {
      get { return text_ != null; }
    }
    /// <summary>Clears the value of the "text" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearText() {
      text_ = null;
    }

    /// <summary>Field number for the "oco_order_no" field.</summary>
    public const int OcoOrderNoFieldNumber = 8;
    private readonly static long OcoOrderNoDefaultValue = 0L;

    private long ocoOrderNo_;
    /// <summary>
    ///oco订单号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OcoOrderNo {
      get { if ((_hasBits0 & 2) != 0) { return ocoOrderNo_; } else { return OcoOrderNoDefaultValue; } }
      set {
        _hasBits0 |= 2;
        ocoOrderNo_ = value;
      }
    }
    /// <summary>Gets whether the "oco_order_no" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOcoOrderNo {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "oco_order_no" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOcoOrderNo() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "orders" field.</summary>
    public const int OrdersFieldNumber = 98;
    private static readonly pb::FieldCodec<global::Ctrade.Message.APIOcoOrderSubmitReply> _repeated_orders_codec
        = pb::FieldCodec.ForMessage(786, global::Ctrade.Message.APIOcoOrderSubmitReply.Parser);
    private readonly pbc::RepeatedField<global::Ctrade.Message.APIOcoOrderSubmitReply> orders_ = new pbc::RepeatedField<global::Ctrade.Message.APIOcoOrderSubmitReply>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Ctrade.Message.APIOcoOrderSubmitReply> Orders {
      get { return orders_; }
    }

    /// <summary>Field number for the "usr" field.</summary>
    public const int UsrFieldNumber = 100;
    private global::Ctrade.Message.User usr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.User Usr {
      get { return usr_; }
      set {
        usr_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOcoOrderSumitReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOcoOrderSumitReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mkt != other.Mkt) return false;
      if (ExecAckStatus != other.ExecAckStatus) return false;
      if (TranTime != other.TranTime) return false;
      if (OrderReqId != other.OrderReqId) return false;
      if (Text != other.Text) return false;
      if (OcoOrderNo != other.OcoOrderNo) return false;
      if(!orders_.Equals(other.orders_)) return false;
      if (!object.Equals(Usr, other.Usr)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMkt) hash ^= Mkt.GetHashCode();
      if (HasExecAckStatus) hash ^= ExecAckStatus.GetHashCode();
      if (HasTranTime) hash ^= TranTime.GetHashCode();
      if (HasOrderReqId) hash ^= OrderReqId.GetHashCode();
      if (HasText) hash ^= Text.GetHashCode();
      if (HasOcoOrderNo) hash ^= OcoOrderNo.GetHashCode();
      hash ^= orders_.GetHashCode();
      if (usr_ != null) hash ^= Usr.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasMkt) {
        output.WriteRawTag(8);
        output.WriteInt32(Mkt);
      }
      if (HasExecAckStatus) {
        output.WriteRawTag(18);
        output.WriteString(ExecAckStatus);
      }
      if (HasTranTime) {
        output.WriteRawTag(26);
        output.WriteString(TranTime);
      }
      if (HasOrderReqId) {
        output.WriteRawTag(50);
        output.WriteString(OrderReqId);
      }
      if (HasText) {
        output.WriteRawTag(58);
        output.WriteString(Text);
      }
      if (HasOcoOrderNo) {
        output.WriteRawTag(64);
        output.WriteInt64(OcoOrderNo);
      }
      orders_.WriteTo(output, _repeated_orders_codec);
      if (usr_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Usr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasMkt) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Mkt);
      }
      if (HasExecAckStatus) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExecAckStatus);
      }
      if (HasTranTime) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TranTime);
      }
      if (HasOrderReqId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrderReqId);
      }
      if (HasText) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (HasOcoOrderNo) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OcoOrderNo);
      }
      size += orders_.CalculateSize(_repeated_orders_codec);
      if (usr_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Usr);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOcoOrderSumitReply other) {
      if (other == null) {
        return;
      }
      if (other.HasMkt) {
        Mkt = other.Mkt;
      }
      if (other.HasExecAckStatus) {
        ExecAckStatus = other.ExecAckStatus;
      }
      if (other.HasTranTime) {
        TranTime = other.TranTime;
      }
      if (other.HasOrderReqId) {
        OrderReqId = other.OrderReqId;
      }
      if (other.HasText) {
        Text = other.Text;
      }
      if (other.HasOcoOrderNo) {
        OcoOrderNo = other.OcoOrderNo;
      }
      orders_.Add(other.orders_);
      if (other.usr_ != null) {
        if (usr_ == null) {
          Usr = new global::Ctrade.Message.User();
        }
        Usr.MergeFrom(other.Usr);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Mkt = input.ReadInt32();
            break;
          }
          case 18: {
            ExecAckStatus = input.ReadString();
            break;
          }
          case 26: {
            TranTime = input.ReadString();
            break;
          }
          case 50: {
            OrderReqId = input.ReadString();
            break;
          }
          case 58: {
            Text = input.ReadString();
            break;
          }
          case 64: {
            OcoOrderNo = input.ReadInt64();
            break;
          }
          case 786: {
            orders_.AddEntriesFrom(input, _repeated_orders_codec);
            break;
          }
          case 802: {
            if (usr_ == null) {
              Usr = new global::Ctrade.Message.User();
            }
            input.ReadMessage(Usr);
            break;
          }
        }
      }
    }

  }

  public sealed partial class APIOcoOrderSumitReplyMsg : pb::IMessage<APIOcoOrderSumitReplyMsg> {
    private static readonly pb::MessageParser<APIOcoOrderSumitReplyMsg> _parser = new pb::MessageParser<APIOcoOrderSumitReplyMsg>(() => new APIOcoOrderSumitReplyMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOcoOrderSumitReplyMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOcoOrderSumitReplyMsgReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSumitReplyMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSumitReplyMsg(APIOcoOrderSumitReplyMsg other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      body_ = other.body_ != null ? other.body_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderSumitReplyMsg Clone() {
      return new APIOcoOrderSumitReplyMsg(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Ctrade.Message.Header header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 2;
    private global::Ctrade.Message.APIOcoOrderSumitReply body_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.APIOcoOrderSumitReply Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOcoOrderSumitReplyMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOcoOrderSumitReplyMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Body, other.Body)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (body_ != null) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (body_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOcoOrderSumitReplyMsg other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Ctrade.Message.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::Ctrade.Message.APIOcoOrderSumitReply();
        }
        Body.MergeFrom(other.Body);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Ctrade.Message.Header();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (body_ == null) {
              Body = new global::Ctrade.Message.APIOcoOrderSumitReply();
            }
            input.ReadMessage(Body);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
