// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: APIOcoOrderCancelRequestMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ctrade.Message {

  /// <summary>Holder for reflection information generated from APIOcoOrderCancelRequestMsg.proto</summary>
  public static partial class APIOcoOrderCancelRequestMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for APIOcoOrderCancelRequestMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static APIOcoOrderCancelRequestMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFBUElPY29PcmRlckNhbmNlbFJlcXVlc3RNc2cucHJvdG8SDmN0cmFkZS5t",
            "ZXNzYWdlGg5zdGFuZGFyZC5wcm90bxoMSGVhZGVyLnByb3RvGgpVc2VyLnBy",
            "b3RvInAKGEFQSU9jb09yZGVyQ2FuY2VsUmVxdWVzdBILCgNta3QYASABKAUS",
            "EwoLb2NvX29yZHJfaWQYAiABKAkSDgoGdXNyX25tGAMgASgJEiIKBHVzZXIY",
            "ZCACKAsyFC5jdHJhZGUubWVzc2FnZS5Vc2VyIn0KG0FQSU9jb09yZGVyQ2Fu",
            "Y2VsUmVxdWVzdE1zZxImCgZoZWFkZXIYASABKAsyFi5jdHJhZGUubWVzc2Fn",
            "ZS5IZWFkZXISNgoEYm9keRgCIAEoCzIoLmN0cmFkZS5tZXNzYWdlLkFQSU9j",
            "b09yZGVyQ2FuY2VsUmVxdWVzdEI6ChVjbi5jb20uY2ZldHMuZGF0YS5tc2dC",
            "IUFQSU9jb09yZGVyQ2FuY2VsUmVxdWVzdE1zZ1Byb2J1Zg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::StandardReflection.Descriptor, global::Ctrade.Message.HeaderReflection.Descriptor, global::Ctrade.Message.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOcoOrderCancelRequest), global::Ctrade.Message.APIOcoOrderCancelRequest.Parser, new[]{ "Mkt", "OcoOrdrId", "UsrNm", "User" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ctrade.Message.APIOcoOrderCancelRequestMsg), global::Ctrade.Message.APIOcoOrderCancelRequestMsg.Parser, new[]{ "Header", "Body" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///cancle order message
  /// </summary>
  public sealed partial class APIOcoOrderCancelRequest : pb::IMessage<APIOcoOrderCancelRequest> {
    private static readonly pb::MessageParser<APIOcoOrderCancelRequest> _parser = new pb::MessageParser<APIOcoOrderCancelRequest>(() => new APIOcoOrderCancelRequest());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOcoOrderCancelRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOcoOrderCancelRequestMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelRequest(APIOcoOrderCancelRequest other) : this() {
      _hasBits0 = other._hasBits0;
      mkt_ = other.mkt_;
      ocoOrdrId_ = other.ocoOrdrId_;
      usrNm_ = other.usrNm_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelRequest Clone() {
      return new APIOcoOrderCancelRequest(this);
    }

    /// <summary>Field number for the "mkt" field.</summary>
    public const int MktFieldNumber = 1;
    private readonly static int MktDefaultValue = 0;

    private int mkt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Mkt {
      get { if ((_hasBits0 & 1) != 0) { return mkt_; } else { return MktDefaultValue; } }
      set {
        _hasBits0 |= 1;
        mkt_ = value;
      }
    }
    /// <summary>Gets whether the "mkt" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMkt {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "mkt" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMkt() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "oco_ordr_id" field.</summary>
    public const int OcoOrdrIdFieldNumber = 2;
    private readonly static string OcoOrdrIdDefaultValue = "";

    private string ocoOrdrId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OcoOrdrId {
      get { return ocoOrdrId_ ?? OcoOrdrIdDefaultValue; }
      set {
        ocoOrdrId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "oco_ordr_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOcoOrdrId {
      get { return ocoOrdrId_ != null; }
    }
    /// <summary>Clears the value of the "oco_ordr_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOcoOrdrId() {
      ocoOrdrId_ = null;
    }

    /// <summary>Field number for the "usr_nm" field.</summary>
    public const int UsrNmFieldNumber = 3;
    private readonly static string UsrNmDefaultValue = "";

    private string usrNm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UsrNm {
      get { return usrNm_ ?? UsrNmDefaultValue; }
      set {
        usrNm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "usr_nm" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUsrNm {
      get { return usrNm_ != null; }
    }
    /// <summary>Clears the value of the "usr_nm" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUsrNm() {
      usrNm_ = null;
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 100;
    private global::Ctrade.Message.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOcoOrderCancelRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOcoOrderCancelRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mkt != other.Mkt) return false;
      if (OcoOrdrId != other.OcoOrdrId) return false;
      if (UsrNm != other.UsrNm) return false;
      if (!object.Equals(User, other.User)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMkt) hash ^= Mkt.GetHashCode();
      if (HasOcoOrdrId) hash ^= OcoOrdrId.GetHashCode();
      if (HasUsrNm) hash ^= UsrNm.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasMkt) {
        output.WriteRawTag(8);
        output.WriteInt32(Mkt);
      }
      if (HasOcoOrdrId) {
        output.WriteRawTag(18);
        output.WriteString(OcoOrdrId);
      }
      if (HasUsrNm) {
        output.WriteRawTag(26);
        output.WriteString(UsrNm);
      }
      if (user_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(User);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasMkt) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Mkt);
      }
      if (HasOcoOrdrId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OcoOrdrId);
      }
      if (HasUsrNm) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UsrNm);
      }
      if (user_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOcoOrderCancelRequest other) {
      if (other == null) {
        return;
      }
      if (other.HasMkt) {
        Mkt = other.Mkt;
      }
      if (other.HasOcoOrdrId) {
        OcoOrdrId = other.OcoOrdrId;
      }
      if (other.HasUsrNm) {
        UsrNm = other.UsrNm;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Ctrade.Message.User();
        }
        User.MergeFrom(other.User);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Mkt = input.ReadInt32();
            break;
          }
          case 18: {
            OcoOrdrId = input.ReadString();
            break;
          }
          case 26: {
            UsrNm = input.ReadString();
            break;
          }
          case 802: {
            if (user_ == null) {
              User = new global::Ctrade.Message.User();
            }
            input.ReadMessage(User);
            break;
          }
        }
      }
    }

  }

  public sealed partial class APIOcoOrderCancelRequestMsg : pb::IMessage<APIOcoOrderCancelRequestMsg> {
    private static readonly pb::MessageParser<APIOcoOrderCancelRequestMsg> _parser = new pb::MessageParser<APIOcoOrderCancelRequestMsg>(() => new APIOcoOrderCancelRequestMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIOcoOrderCancelRequestMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ctrade.Message.APIOcoOrderCancelRequestMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelRequestMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelRequestMsg(APIOcoOrderCancelRequestMsg other) : this() {
      header_ = other.header_ != null ? other.header_.Clone() : null;
      body_ = other.body_ != null ? other.body_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIOcoOrderCancelRequestMsg Clone() {
      return new APIOcoOrderCancelRequestMsg(this);
    }

    /// <summary>Field number for the "header" field.</summary>
    public const int HeaderFieldNumber = 1;
    private global::Ctrade.Message.Header header_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.Header Header {
      get { return header_; }
      set {
        header_ = value;
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 2;
    private global::Ctrade.Message.APIOcoOrderCancelRequest body_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Ctrade.Message.APIOcoOrderCancelRequest Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIOcoOrderCancelRequestMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIOcoOrderCancelRequestMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Header, other.Header)) return false;
      if (!object.Equals(Body, other.Body)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (header_ != null) hash ^= Header.GetHashCode();
      if (body_ != null) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (header_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Header);
      }
      if (body_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (header_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Header);
      }
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIOcoOrderCancelRequestMsg other) {
      if (other == null) {
        return;
      }
      if (other.header_ != null) {
        if (header_ == null) {
          Header = new global::Ctrade.Message.Header();
        }
        Header.MergeFrom(other.Header);
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::Ctrade.Message.APIOcoOrderCancelRequest();
        }
        Body.MergeFrom(other.Body);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (header_ == null) {
              Header = new global::Ctrade.Message.Header();
            }
            input.ReadMessage(Header);
            break;
          }
          case 18: {
            if (body_ == null) {
              Body = new global::Ctrade.Message.APIOcoOrderCancelRequest();
            }
            input.ReadMessage(Body);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
