// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: standard.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from standard.proto</summary>
public static partial class StandardReflection {

  #region Descriptor
  /// <summary>File descriptor for standard.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static StandardReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5zdGFuZGFyZC5wcm90bxogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0b3Iu",
          "cHJvdG86MQoJc2VydmljZUlEEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRp",
          "b25zGNCGAyABKAk6MgoKbWV0aG9kTmFtZRIcLmdvb2dsZS5wcm90b2J1Zi5G",
          "aWxlT3B0aW9ucxjRhgMgASgJOjAKB21ldGFOdW0SHS5nb29nbGUucHJvdG9i",
          "dWYuRmllbGRPcHRpb25zGNKGAyABKAk6MQoIbWV0YURhdGUSHS5nb29nbGUu",
          "cHJvdG9idWYuRmllbGRPcHRpb25zGNOGAyABKAhCJwoLc2FtcGxlLmRlbW9C",
          "GEN1c3RvbWVkT3B0aW9uc0NvbnRhaW5lcg=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { StandardExtensions.ServiceID, StandardExtensions.MethodName, StandardExtensions.MetaNum, StandardExtensions.MetaDate }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of standard.proto</summary>
public static partial class StandardExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FileOptions, string> ServiceID =
    new pb::Extension<global::Google.Protobuf.Reflection.FileOptions, string>(50000, pb::FieldCodec.ForString(400002, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FileOptions, string> MethodName =
    new pb::Extension<global::Google.Protobuf.Reflection.FileOptions, string>(50001, pb::FieldCodec.ForString(400010, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> MetaNum =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(50002, pb::FieldCodec.ForString(400018, ""));
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> MetaDate =
    new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50003, pb::FieldCodec.ForBool(400024, false));
}


#endregion Designer generated code
