version: "3.7"
services:

  portalapi:
    build:
        context: DockerFiles
        dockerfile: Dockerfile-PortalApi
    restart: always
    ports:
      - "8081:443"
    ulimits:
        nproc: 65535
        nofile:
            soft: 65535
            hard: 65535
  caseservice:
    build:
        context: DockerFiles
        dockerfile: Dockerfile-CaseService
    restart: always
    ports:
      - "8082:80"
    ulimits:
        nproc: 65535
        nofile:
            soft: 65535
            hard: 65535
  portalweb:
    build:
        context: DockerFiles
        dockerfile: Dockerfile-PortalWeb
    restart: always
    ports:
      - "80:80"
    privileged: true
